# Generated by Django 4.2.2 on 2023-06-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_section_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='show_if_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_questions', to='questionnaires.questionoption'),
        ),
    ]
