# Generated by Django 4.2.2 on 2023-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_alter_questionoption_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
