# Generated by Django 4.2.2 on 2023-06-27 15:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_question_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text_es',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='info_text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='info_text_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='info_text_es',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True),
        ),
    ]
