# Generated by Django 5.0.4 on 2024-04-30 09:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_alter_question_help_text_alter_question_help_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='help_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='help_text_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='info_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='info_text_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='info_text_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=300, null=True),
        ),
    ]
