# Generated by Django 4.2.2 on 2023-06-28 09:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', ckeditor.fields.RichTextField(blank=True)),
                ('info', ckeditor.fields.RichTextField(blank=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
