# Generated by Django 4.2.2 on 2023-06-28 09:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_contentsiteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsiteconfig',
            name='home_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsiteconfig',
            name='home_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsiteconfig',
            name='info_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsiteconfig',
            name='info_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
